/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package primero_siguiente_GUI;

import P_Grammar_things.C_Production;
import javax.swing.JOptionPane;

/**
 *
 * @author devcrack
 */
public class main extends javax.swing.JFrame {
    int n_error;
    /**
     * Creates new form main
     */
    public main() {
        initComponents();
        this.n_error = 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_Work_Field = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTxt_Area_wrk_field = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jBtt_Iniciar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenItem_Abrir = new javax.swing.JMenuItem();
        jMenIt_guardar = new javax.swing.JMenuItem();
        jMen_It_Cerrar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel_Work_Field.setBorder(javax.swing.BorderFactory.createTitledBorder("Area de Trabajo"));

        jTxt_Area_wrk_field.setColumns(20);
        jTxt_Area_wrk_field.setRows(5);
        jTxt_Area_wrk_field.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTxt_Area_wrk_fieldKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTxt_Area_wrk_field);

        javax.swing.GroupLayout jPanel_Work_FieldLayout = new javax.swing.GroupLayout(jPanel_Work_Field);
        jPanel_Work_Field.setLayout(jPanel_Work_FieldLayout);
        jPanel_Work_FieldLayout.setHorizontalGroup(
            jPanel_Work_FieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
        );
        jPanel_Work_FieldLayout.setVerticalGroup(
            jPanel_Work_FieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
        );

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jBtt_Iniciar.setText("Iniciar");

        jMenu1.setText("File");

        jMenItem_Abrir.setText("Abrir");
        jMenu1.add(jMenItem_Abrir);

        jMenIt_guardar.setText("Guardar");
        jMenu1.add(jMenIt_guardar);

        jMen_It_Cerrar.setText("Cerrar");
        jMenu1.add(jMen_It_Cerrar);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel_Work_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBtt_Iniciar)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel_Work_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jBtt_Iniciar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxt_Area_wrk_fieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxt_Area_wrk_fieldKeyPressed
        if
        (
            evt.getKeyChar() =='\''
            ||
            evt.getKeyChar() == '-'
            ||
            evt.getKeyChar() == '\\'
            ||
            evt.getKeyChar() == '_'
            ||
            evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9'
            ||
            evt.getKeyChar() == '>'
            ||
            evt.getKeyChar() == '<'
            ||
            evt.getKeyChar() == '~'
            ||
            evt.getKeyChar() == '|'
            ||
            evt.getKeyChar() >= 'a' && evt.getKeyChar() <= 'z'
            ||
            evt.getKeyChar() >= 'A' && evt.getKeyChar() <= 'Z'
            ||
            evt.getKeyChar() =='*'
            ||
            evt.getKeyChar() =='+'
            ||   
            evt.getKeyChar() == '+'
            ||
            evt.getKeyCode() == 8
            ||
             evt.getKeyCode() == 10
        )
        {
            if(evt.getKeyCode() == 10)
            {
                String lines[];
                boolean flag;
               
                lines = this.jTxt_Area_wrk_field.getText().split("\n");
                flag = C_Production.check_production(lines[lines.length - 1]);
                this.jTextArea2.setText(String.valueOf(flag));
                this.jTxt_Area_wrk_field.setEditable(flag);
                
                if(flag)
                {}
                else
                {
                    Object[] options = {"OK"};
                    this.n_error = JOptionPane.showOptionDialog(this,
                            "Error en el formato de la produccion",
                            "ERROR", JOptionPane.PLAIN_MESSAGE,
                            JOptionPane.ERROR_MESSAGE, null, options, options[0]);
                    if( n_error == JOptionPane.OK_OPTION)
                        this.jTxt_Area_wrk_field.getCaret().setVisible(true);
                    n_error = 0;
                }
            }
            else
                this.jTxt_Area_wrk_field.setEditable(true);
        }
        else
            this.jTxt_Area_wrk_field.setEditable(false);
    }//GEN-LAST:event_jTxt_Area_wrk_fieldKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtt_Iniciar;
    private javax.swing.JMenuItem jMenIt_guardar;
    private javax.swing.JMenuItem jMenItem_Abrir;
    private javax.swing.JMenuItem jMen_It_Cerrar;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel_Work_Field;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTxt_Area_wrk_field;
    // End of variables declaration//GEN-END:variables
}
